---
- name: Install and configure nginx as a reverse proxy
  hosts: pi4-1
  become: yes  # This is optional; use if you require elevated privileges
  gather_facts: true
  vars_files:
    - /root/.ansible/homelab_secrets.yml

  roles:
    - name: homelab-nginx